#!/usr/bin/env python3
"""Focused second-pass sensitivities for baseline coverage and pre-index RASS."""

from __future__ import annotations

import os

import importlib.util
from pathlib import Path

import pandas as pd


ROOT = Path(os.environ.get("SEDATION_PROJECT_ROOT", Path(__file__).resolve().parents[1])).expanduser().resolve()
OUT = ROOT / "outputs" / "active_comparator_sedation"


def load_module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def clean_saved_cohort(frame):
    """Remove columns generated by the previous propensity-score fit."""
    exact = {
        "age10", "weight10", "map10", "hr10", "index6", "bp_obs_log",
        "hr_obs_log", "ps", "overlap_weight",
    }
    prefixes = ("unit_type_", "admission_source_", "anchor_year_group_")
    hospital_dummy = [
        col for col in frame.columns
        if col.startswith("hospital_id_") and col != "hospital_id"
    ]
    generated = [
        col for col in frame.columns
        if col in exact or col.startswith(prefixes)
    ] + hospital_dummy
    return frame.drop(columns=sorted(set(generated)), errors="ignore")


def main():
    base = load_module("active_comparator", ROOT / "work" / "active_comparator_sedation_study.py")
    hourly = load_module("hourly", ROOT / "work" / "harmonized_hourly_outcome.py")
    results = []

    for database, prefix in (("eICU-CRD", "eicu"), ("MIMIC-IV", "mimic")):
        frame = pd.read_csv(OUT / f"{prefix}_harmonized_hourly_weighted_analysis_cohort.csv")
        frame = clean_saved_cohort(frame)

        dense_baseline = frame[
            frame.baseline_bp_hour_bins.ge(3)
            & frame.baseline_hr_hour_bins.ge(3)
        ].copy()
        _, rows, _ = hourly.analyze_harmonized(
            base, dense_baseline, database,
            analysis_label="at_least_3_baseline_hour_bins",
            n_boot=1000,
            outcomes=["hourly_repeated_instability_24h"],
        )
        results.extend(rows)

        if database == "MIMIC-IV":
            missing_indicator = frame.copy()
            missing_indicator["baseline_rass_observed"] = missing_indicator.baseline_rass.notna().astype(int)
            missing_indicator["baseline_rass_filled"] = missing_indicator.baseline_rass.fillna(0)
            _, rows, _ = hourly.analyze_harmonized(
                base, missing_indicator, database,
                analysis_label="rass_missing_indicator_adjusted",
                n_boot=1000,
                outcomes=["hourly_repeated_instability_24h"],
                extra_covariates=["baseline_rass_observed", "baseline_rass_filled"],
            )
            results.extend(rows)

            rass_complete = frame[frame.baseline_rass.notna()].copy()
            _, rows, _ = hourly.analyze_harmonized(
                base, rass_complete, database,
                analysis_label="rass_complete_case_adjusted",
                n_boot=1000,
                outcomes=["hourly_repeated_instability_24h"],
                extra_covariates=["baseline_rass"],
            )
            results.extend(rows)

    output = pd.DataFrame(results)
    output.to_csv(
        OUT / "table21_additional_harmonized_sensitivity.csv",
        index=False, encoding="utf-8-sig",
    )
    print(output.to_string(index=False))


if __name__ == "__main__":
    main()
